name: Package Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/global.json
        cache: true
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build & Pack
      run: dotnet build --no-restore --configuration Release
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - name: Publish
      working-directory: src
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push SourceLink-Library/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -- source "github
