name: Package Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/global.json
        cache: true
        cache-dependency-path: src/packages.lock.json
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build & Pack
      run: dotnet build --no-restore --configuration Release
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src
    - run: cat /home/runner/work/sourcelink-library/nuget.config
    - name: Publish
      working-directory: src
      env:
        TOKEN: ${{ github.token }}
      run: |
        dotnet pack --no-restore --configuration Release -o ${{ runner.temp }}/publish
        dotnet nuget push ${{ runner.temp }}/publish/*.nupkg
